"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def parse_bool_env(value, default=False):
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def parse_csv_env(value, default=None):
    if not value:
        return default or []
    parsed = []
    for item in value.split(","):
        cleaned = item.strip().strip("\"'")
        if cleaned:
            parsed.append(cleaned)
    return parsed


def load_environment_variables():
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        if key and key not in os.environ:
            os.environ[key] = value


load_environment_variables()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY must be set in the environment or in the .env file before running the project.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = parse_bool_env(os.getenv("DEBUG"), default=True)
ALLOWED_HOSTS = parse_csv_env(
    os.getenv("ALLOWED_HOSTS"),
    default=["localhost", "127.0.0.1"],
)

# Render sets this automatically for web services.
render_hostname = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip().strip("\"'")
if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)

vercel_hostname = os.getenv("VERCEL_URL", "").strip().strip("\"'")
if vercel_hostname:
    if "://" in vercel_hostname:
        vercel_hostname = vercel_hostname.split("://", 1)[1]
    if vercel_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(vercel_hostname)

# Helpful default when deploying on Vercel previews and production domains.
if parse_bool_env(os.getenv("VERCEL"), default=False) and ".vercel.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".vercel.app")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tbotapp',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.db_connection_middleware.ForceCloseDbConnectionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = parse_csv_env(
    os.getenv("CORS_ALLOWED_ORIGINS"),
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:4173",
        "http://127.0.0.1:4173",
    ],
)

CSRF_TRUSTED_ORIGINS = parse_csv_env(
    os.getenv("CSRF_TRUSTED_ORIGINS"),
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
)

if vercel_hostname:
    vercel_origin = f"https://{vercel_hostname}"
    if vercel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(vercel_origin)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE')
if not DB_ENGINE:
    # Prefer MySQL only when the full MySQL connection set is available.
    if os.getenv('DB_HOST') and os.getenv('DB_NAME') and os.getenv('DB_USER'):
        DB_ENGINE = 'django.db.backends.mysql'
    else:
        DB_ENGINE = 'django.db.backends.sqlite3'

if DB_ENGINE == 'django.db.backends.mysql':

    db_options = {}
    db_conn_max_age = os.getenv("DB_CONN_MAX_AGE", "").strip()
    if db_conn_max_age:
        try:
            conn_max_age = int(db_conn_max_age)
        except ValueError:
            conn_max_age = 0
    else:
        # Serverless functions should avoid persistent DB connections.
        conn_max_age = 0 if parse_bool_env(os.getenv("VERCEL"), default=False) else 60

    db_ssl_default = parse_bool_env(os.getenv("VERCEL"), default=False)
    if parse_bool_env(os.getenv("DB_SSL"), default=db_ssl_default):
        # PyMySQL enables TLS when ssl options are provided; empty dict allows
        # the default cert chain on providers that require encrypted transport.
        db_options["ssl"] = {}

    db_connect_timeout = os.getenv("DB_CONNECT_TIMEOUT", "").strip()
    if not db_connect_timeout and parse_bool_env(os.getenv("VERCEL"), default=False):
        db_connect_timeout = "10"
    if db_connect_timeout:
        try:
            db_options["connect_timeout"] = int(db_connect_timeout)
        except ValueError:
            pass

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': int(os.getenv('DB_PORT', '3306')),
            'CONN_MAX_AGE': conn_max_age,
            'OPTIONS': db_options,
        }
    }
elif DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise RuntimeError(f"Unsupported DB_ENGINE: {DB_ENGINE}")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
