"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
import cloudinary

# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT HELPERS
# ============================================================

def parse_bool_env(value, default=False):
    if value is None:
        return default

    return str(value).strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def parse_csv_env(value, default=None):
    if not value:
        return default or []

    parsed = []

    for item in value.split(","):
        cleaned = item.strip().strip("\"'")

        if cleaned:
            parsed.append(cleaned)

    return parsed


def load_environment_variables():
    """
    Load variables from .env when running locally.

    Locally, .env should win over stale shell/session
    environment variables.

    In production (Render), real platform environment
    variables always take priority.
    """

    if os.getenv("RENDER"):
        return

    env_path = BASE_DIR / ".env"

    if not env_path.exists():
        return

    for line in env_path.read_text(
        encoding="utf-8"
    ).splitlines():

        line = line.strip()

        if (
            not line
            or line.startswith("#")
            or "=" not in line
        ):
            continue

        key, value = line.split("=", 1)

        key = key.strip()
        value = value.strip().strip("\"'")

        if key:
            os.environ[key] = value


load_environment_variables()


# ============================================================
# DISCORD OAUTH2
# ============================================================

DISCORD_CLIENT_ID = os.getenv("DISCORD_CLIENT_ID")

DISCORD_CLIENT_SECRET = os.getenv(
    "DISCORD_CLIENT_SECRET"
)

DISCORD_REDIRECT_URI = os.getenv(
    "DISCORD_REDIRECT_URI",
    "http://localhost:8000/auth/discord/callback/",
)


if not DISCORD_CLIENT_ID:
    raise RuntimeError(
        "DISCORD_CLIENT_ID must be set in the environment "
        "or in the .env file."
    )


if not DISCORD_CLIENT_SECRET:
    raise RuntimeError(
        "DISCORD_CLIENT_SECRET must be set in the environment "
        "or in the .env file."
    )


# ============================================================
# DISCORD OWNER
# ============================================================

DISCORD_OWNER_ID = os.getenv(
    "DISCORD_OWNER_ID"
)

if not DISCORD_OWNER_ID:
    raise RuntimeError(
        "DISCORD_OWNER_ID must be set in the environment "
        "or in the .env file."
    )


# ============================================================
# FRONTEND
# ============================================================

FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://localhost:5173",
).rstrip("/")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY must be set in the environment "
        "or in the .env file before running the project."
    )


# ============================================================
# DEBUG
# ============================================================

DEBUG = parse_bool_env(
    os.getenv("DEBUG"),
    default=True,
)


# ============================================================
# ALLOWED HOSTS
# ============================================================

ALLOWED_HOSTS = parse_csv_env(
    os.getenv("ALLOWED_HOSTS"),
    default=[
        "localhost",
        "127.0.0.1",
    ],
)

# ============================================================
# CLOUDINARY
# ============================================================

CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True,
)
# ============================================================
# RENDER HOSTNAME
# ============================================================

render_hostname = os.getenv(
    "RENDER_EXTERNAL_HOSTNAME",
    "",
).strip().strip("\"'")


if (
    render_hostname
    and render_hostname not in ALLOWED_HOSTS
):
    ALLOWED_HOSTS.append(render_hostname)


# ============================================================
# VERCEL HOSTNAME
# ============================================================

vercel_hostname = os.getenv(
    "VERCEL_URL",
    "",
).strip().strip("\"'")


if vercel_hostname:

    if "://" in vercel_hostname:
        vercel_hostname = vercel_hostname.split(
            "://",
            1,
        )[1]

    if vercel_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(vercel_hostname)


# ============================================================
# VERCEL PREVIEWS
# ============================================================

if (
    parse_bool_env(
        os.getenv("VERCEL"),
        default=False,
    )
    and ".vercel.app" not in ALLOWED_HOSTS
):
    ALLOWED_HOSTS.append(".vercel.app")


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "tbotapp",

    "rest_framework",
    "corsheaders",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
}
# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# CORS
# ============================================================

CORS_ALLOWED_ORIGINS = parse_csv_env(
    os.getenv("CORS_ALLOWED_ORIGINS"),
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:4173",
        "http://127.0.0.1:4173",
    ],
)

# IMPORTANT:
# Allows the browser to send Django's session cookie
# with requests from the React frontend.
CORS_ALLOW_CREDENTIALS = True


# ============================================================
# CSRF
# ============================================================

CSRF_TRUSTED_ORIGINS = parse_csv_env(
    os.getenv("CSRF_TRUSTED_ORIGINS"),
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:4173",
        "http://127.0.0.1:4173",
    ],
)


if vercel_hostname:

    vercel_origin = f"https://{vercel_hostname}"

    if vercel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(
            vercel_origin
        )


# ============================================================
# SESSION / AUTHENTICATION COOKIES
# ============================================================

# JavaScript cannot directly read the Django session cookie.
SESSION_COOKIE_HTTPONLY = True

# Allows the session cookie to work between your
# React frontend and Django backend during local development.
SESSION_COOKIE_SAMESITE = "Lax"

# localhost development uses HTTP, not HTTPS.
SESSION_COOKIE_SECURE = False


# ============================================================
# PROXY / HTTPS
# ============================================================

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

USE_X_FORWARDED_HOST = True


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "core.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django.DjangoTemplates"
        ),

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================
# DATABASE
# ============================================================
#
# Neon PostgreSQL ONLY
#
# Local:
#
# DATABASE_URL=postgresql://user:password@host/db?sslmode=require
#
# Production:
#
# DATABASE_URL should be configured in Render's
# environment variables.
#
# There is NO SQLite fallback.
# ============================================================

DATABASE_URL = os.getenv("DATABASE_URL")


if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL is not configured. "
        "This project requires a Neon PostgreSQL database."
    )


DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,
        conn_health_checks=True,
    )
}


# Neon requires SSL.
DATABASES["default"]["OPTIONS"] = {
    "sslmode": "require",
    "connect_timeout": 10,
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"
# ============================================================
# MEDIA / UPLOADED FILES
# ============================================================



# ============================================================
# DEFAULT FILE STORAGE
# ============================================================

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}