# Generated by Django 6.0.7 on 2026-08-22 20:47

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decklist',
            fields=[
                ('deckid', models.IntegerField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=30)),
                ('hero', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(db_column='category', max_length=30)),
                ('archetype', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1500)),
                ('deck_doc', models.CharField(blank=True, max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('creator', models.CharField(blank=True, max_length=300)),
                ('optimization', models.CharField(blank=True, max_length=60)),
                ('inspiration', models.CharField(blank=True, max_length=60)),
                ('cost', models.CharField(blank=True, max_length=10)),
                ('aliases', models.CharField(blank=True, max_length=300)),
                ('cards', models.CharField(blank=True, max_length=400)),
                ('suggested_date', models.CharField(blank=True, max_length=20)),
                ('updated_date', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'web_decks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeepOrScrap',
            fields=[
                ('tierid', models.IntegerField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=40)),
                ('card_class', models.CharField(db_column='class', max_length=30)),
                ('image', models.CharField(blank=True, max_length=400)),
                ('reasoning', models.CharField(blank=True, max_length=1500)),
                ('creator', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'web_keep_or_scrap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyDecklist',
            fields=[
                ('deckid', models.IntegerField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=30)),
                ('hero', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(db_column='category', max_length=30)),
                ('archetype', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1500)),
                ('deck_doc', models.CharField(blank=True, max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('creator', models.CharField(blank=True, max_length=300)),
                ('optimization', models.CharField(blank=True, max_length=60)),
                ('inspiration', models.CharField(blank=True, max_length=60)),
                ('cost', models.CharField(blank=True, max_length=10)),
                ('aliases', models.CharField(blank=True, max_length=300)),
                ('cards', models.CharField(blank=True, max_length=1000)),
                ('suggested_date', models.CharField(blank=True, max_length=20)),
                ('updated_date', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'web_legacy_decks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('hero', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('archetype', models.CharField(max_length=255)),
                ('creator', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, max_length=255, null=True)),
                ('cards', models.TextField(blank=True, null=True)),
                ('inspiration', models.CharField(blank=True, max_length=255, null=True)),
                ('optimization', models.CharField(blank=True, max_length=255, null=True)),
                ('suggested_date', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=255, null=True)),
                ('deck_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('modified_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'user_decks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discord_id', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('profile_slug', models.CharField(max_length=100, unique=True)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebCards',
            fields=[
                ('cardid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(max_length=50)),
                ('card_name', models.CharField(blank=True, max_length=200)),
                ('side', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('stats', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('ability', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.CharField(blank=True, max_length=330)),
                ('traits', models.CharField(blank=True, max_length=150)),
                ('set_rarity', models.CharField(blank=True, max_length=50)),
                ('flavor_text', models.CharField(blank=True, max_length=300)),
                ('aliases', models.CharField(blank=True, max_length=160)),
                ('button', models.CharField(blank=True, max_length=130)),
                ('button_emoji', models.CharField(blank=True, max_length=130)),
                ('button2', models.CharField(blank=True, max_length=130)),
                ('button_emoji2', models.CharField(blank=True, max_length=130)),
            ],
            options={
                'db_table': 'web_cards',
                'managed': False,
            },
        ),
    ]
